"""Generate markdown summary report from test results."""

import csv
import json
import os
from datetime import datetime


def _load_json(path):
  if not os.path.exists(path):
    return None
  with open(path) as f:
    return json.load(f)


def _load_csv(path):
  if not os.path.exists(path):
    return None
  with open(path) as f:
    return list(csv.DictReader(f))


def generate_report(results_dir, output_path=None):
  """Generate a markdown report from test results.

  Args:
    results_dir: Path to timestamped results directory.
    output_path: Output file path. Defaults to results_dir/reports/summary.md.

  Returns:
    The generated markdown string.
  """
  if output_path is None:
    output_path = os.path.join(results_dir, "reports", "summary.md")

  lines = []
  lines.append("# AD Testing Suite — Results Summary")
  lines.append(f"\nGenerated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
  lines.append(f"Results directory: `{results_dir}`\n")

  # --- Math results ---
  lines.append("## Mathematical Correctness\n")

  jac_data = _load_json(os.path.join(results_dir, "math", "jacobian_comparison.json"))
  if jac_data:
    tests = jac_data.get("tests", [])
    passed = sum(1 for t in tests if t.get("passed", False))
    lines.append(f"**Jacobian AD vs FD**: {passed}/{len(tests)} passed\n")
    for t in tests:
      status = "PASS" if t.get("passed") else "FAIL"
      lines.append(f"- [{status}] `{t.get('test', 'unknown')}`")
    lines.append("")

  taylor_data = _load_json(os.path.join(results_dir, "math", "taylor_convergence.json"))
  if taylor_data:
    tests = taylor_data.get("tests", [])
    lines.append(f"**Taylor Convergence**: {len(tests)} tests\n")
    for t in tests:
      lines.append(f"- `{t.get('model', '?')}`: slope = {t.get('slope', '?')}")
    lines.append("")

  # --- Performance results ---
  lines.append("## Performance\n")

  overhead_data = _load_csv(os.path.join(results_dir, "perf", "ad_overhead.csv"))
  if overhead_data:
    lines.append("### AD Overhead\n")
    lines.append("| Model | nworld | Time (no AD) | Time (AD) | Overhead |")
    lines.append("|-------|--------|-------------|-----------|----------|")
    for row in overhead_data:
      lines.append(
        f"| {row['model']} | {row['nworld']} | {row['time_no_ad']}s "
        f"| {row['time_ad']}s | {row['overhead_ratio']}x |"
      )
    lines.append("")

  memory_data = _load_csv(os.path.join(results_dir, "perf", "memory_overhead.csv"))
  if memory_data:
    lines.append("### Memory Overhead\n")
    lines.append("| Model | No-AD (bytes) | AD (bytes) | Overhead |")
    lines.append("|-------|--------------|-----------|----------|")
    for row in memory_data:
      lines.append(
        f"| {row['model']} | {row['mem_no_ad_bytes']} "
        f"| {row['mem_ad_bytes']} | {row['overhead_ratio']}x |"
      )
    lines.append("")

  scaling_data = _load_csv(os.path.join(results_dir, "perf", "scaling.csv"))
  if scaling_data:
    lines.append("### Scaling\n")
    lines.append("| Model | DOFs | nworld | Overhead |")
    lines.append("|-------|------|--------|----------|")
    for row in scaling_data:
      lines.append(
        f"| {row['model']} | {row['ndof']} | {row['nworld']} "
        f"| {row['overhead_ratio']}x |"
      )
    lines.append("")

  # --- Visual results ---
  lines.append("## Visual Verification\n")

  traj_data = _load_json(os.path.join(results_dir, "visual", "trajectory_diff.json"))
  if traj_data:
    tests = traj_data.get("tests", [])
    lines.append("### Trajectory Parity\n")
    lines.append("| Model | Max qpos diff | Max qvel diff |")
    lines.append("|-------|--------------|--------------|")
    for t in tests:
      lines.append(
        f"| {t['model']} | {t['max_qpos_diff']:.2e} | {t['max_qvel_diff']:.2e} |"
      )
    lines.append("")

  # Check for gradient maps
  gradient_maps = os.path.join(results_dir, "visual", "gradient_maps")
  if os.path.isdir(gradient_maps):
    pngs = [f for f in os.listdir(gradient_maps) if f.endswith(".png")]
    if pngs:
      lines.append("### Gradient Maps\n")
      for png in sorted(pngs):
        lines.append(f"- `{png}`")
      lines.append("")

  lines.append("---\n*Generated by mjwarp-adtest report generator*\n")

  report = "\n".join(lines)

  os.makedirs(os.path.dirname(output_path), exist_ok=True)
  with open(output_path, "w") as f:
    f.write(report)

  return report
